it_pizza/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from menu.views import *
from sign_up.views import *
from cart.views import *

from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('it_pizza/home/', it_pizza_pizzas, name='pizza_home'),
    path('it_pizza/sign_in/', LoginView.as_view(template_name='log_in.html'),
         name='sign-in'),
    path('it_pizza/sign_out/', LogoutView.as_view(next_page='/'),
         name='log-out'),
    path('it_pizza/sign_up/', it_pizza_sign_up, name='sign-up'),
    path('it_pizza/pizzas/', it_pizza_pizzas, name='pizzas'),
    path('it_pizza/drinks/', it_pizza_drinks, name='drinks'),
    path('it_pizza/deserts/', it_pizza_deserts, name='deserts'),
    path('it_pizza/create_pizza/', it_pizza_create_pizza, name='create_pizza'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from menu.models import *
# Create your models here.
class CartItem(models.Model):
    pizza = models.ForeignKey(Pizzas, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.0)

    def __unicode__(self):
        return "Card item for product {0}".format(str(self.pizza.title))


class Cart(models.Model):
    items = models.ManyToManyField(CartItem, blank=True)
    card_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.0)

    def __str__(self):
        return str(self.id)

menu/models.py
from django.db import models
from sign_up.models import *


# Create your models here.
class Pizzas(models.Model):
    title = models.TextField(max_length=20)
    description = models.TextField(max_length=500)
    price = models.DecimalField(max_digits=50, decimal_places=3, default=0.0)
    mass = models.IntegerField(default=0.0)
    photo = models.ImageField(upload_to='images/', default='DEFAULT VALUE', blank=False)

    def __str__(self):
        return self.title


class OrderPizzas(models.Model):
    user = models.TextField(max_length=20)
    phone_number = models.TextField(max_length=20)

    def __str__(self):
        return self.user


class Drinks(models.Model):
    title = models.TextField(max_length=20)
    price = models.DecimalField(max_digits=50, decimal_places=2, default=0.0)
    ml = models.IntegerField(default=0.0)
    photo = models.ImageField(upload_to='images/', default='DEFAULT VALUE', blank=False)

    def str(self):
        return self.title


class OrderDrinks(models.Model):
    user = models.TextField(max_length=20)
    phone_number = models.TextField(max_length=20)

    def __str__(self):
        return self.user


class Deserts(models.Model):
    title = models.TextField(max_length=20)
    price = models.DecimalField(max_digits=50, decimal_places=2, default=0.0)
    mass = models.IntegerField(default=0.0)
    photo = models.ImageField(upload_to='images/', default='DEFAULT VALUE', blank=False)

    def __str__(self):
        return self.title


class OrderDeserts(models.Model):
    user = models.TextField(max_length=20)
    phone_number = models.TextField(max_length=20)

    def __str__(self):
        return self.user


class CreatePizzas(models.Model):
    title = models.TextField(max_length=20)
    phone_number = models.TextField(max_length=20,default=None)
    cheeze = models.BooleanField(name='Моцарелла', default=False)
    cheeze2 = models.BooleanField(name='Подвійний сир', default=False)
    meet = models.BooleanField(name='Бекон ', default=False)
    meet1 = models.BooleanField(name='Курка ', default=False)
    meet2 = models.BooleanField(name='Шинка', default=False)
    green = models.BooleanField(name='Зелень', default=False)
    pineapple = models.BooleanField(name='Ананас', default=False)
    olives = models.BooleanField(name='Оливки ', default=False)
    tomatoes = models.BooleanField(name='Помідори', default=False)
    pickled_cucumbers = models.BooleanField(name='Мариновані огірки', default=False)
    pepper = models.BooleanField(name='Перець', default=False)
    champignons = models.BooleanField(name='Шампіньйони', default=False)
    maize = models.BooleanField(name='Кукурудза', default=False)

    def __str__(self):
        return self.title

sign_up/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, default=True)

    def __str__(self):
        return str(self.user)

menu/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class CreatePizzasForm(forms.ModelForm):
    class Meta:
        model = CreatePizzas
        exclude = ('users',)


class OrderPizzasForm(forms.ModelForm):
    class Meta:
        model = OrderPizzas
        fields = ('user', 'phone_number')


class OrderDrinksForm(forms.ModelForm):
    class Meta:
        model = OrderDrinks
        fields = ('user', 'phone_number')


class OrderDesertsForm(forms.ModelForm):
    class Meta:
        model = OrderDeserts
        fields = ('user', 'phone_number')

sign_up/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone',)

cart/views.py
from django.shortcuts import render

# Create your views here.

menu/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


# Create your views here.

def home(request):
    return render(request, 'home.html')


def it_pizza_pizzas(request):
    pizzas = Pizzas.objects.all()
    order = OrderPizzasForm(request.POST)
    if request.method == 'POST':
        if order.is_valid():
            orders = order.save(commit=False)
            orders.save()
            return redirect(it_pizza_pizzas)
    context = {'pizzas': pizzas,
               'order': order}
    return render(request, 'pizzas.html', context)


def it_pizza_deserts(request):
    deserts = Deserts.objects.all()
    order = OrderDesertsForm(request.POST)
    if request.method == 'POST':
        if order.is_valid():
            orders = order.save(commit=False)
            orders.save()
            return redirect(it_pizza_pizzas)
    context = {'deserts': deserts,
               'order': order}
    return render(request, 'deserts.html', context)


def it_pizza_drinks(request):
    drinkss = Drinks.objects.all()
    order = OrderDrinksForm(request.POST)
    if request.method == 'POST':
        if order.is_valid():
            orders = order.save(commit=False)
            orders.save()
            return redirect(it_pizza_pizzas)
    context = {'drinkss': drinkss,
               'order': order}
    return render(request, 'drinks.html', context)


def it_pizza_create_pizza(request):
    create_pizza = CreatePizzasForm()
    if request.method == 'POST':
        create_pizza = CreatePizzasForm(request.POST)
        if create_pizza.is_valid():
            pizza = create_pizza.save(commit=False)
            pizza.save()
            return redirect(it_pizza_pizzas)

    return render(request, 'create_pizza.html',
                  {'create': create_pizza})

sign_up/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import *
from menu.views import *


# Create your views here.
def it_pizza_sign_up(request):
    user_form = UserForm(request.POST)
    profile_form = ProfileForm(request.POST)
    if request.method == 'POST':

        if user_form.is_valid() and profile_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_profile_form = profile_form.save(commit=False)
            new_profile_form.user = new_user
            new_profile_form.save()
            user = authenticate(
                username=user_form.cleaned_data['username'],
                password=user_form.cleaned_data['password']
            )
            login(request, user)
            return redirect(it_pizza_pizzas)

    return render(request, 'sign_up.html',
                  {'profile_form': profile_form,
                   'user': user_form})

templates/create_pizza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Зроби свою піццу</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'make.css' %}"/>
    <link rel="stylesheet" href="{% static 'animat.css' %}"/>

</head>
<body>

<header class="header container">
    <div class="wrap-content">
        <ul class="flex-nav">
            <li>
                <a href="{% url 'home' %}" class="">Головна
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a class="bg-a" href="{% url 'pizzas' %}">Піцца ➪
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{% url 'deserts' %}">Десерти
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{% url 'drinks' %}">Напої
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
        </ul>
    </div>
</header>

<div class="container">


    <form method="POST">
        {% csrf_token %}
        <div class="wrap-ta">
            <div class="form-row field-title">
                <label class="required" for="id_title">Ведіть ім'я користувача:</label>
                <textarea placeholder="Ваше ім'я..." class="vLargeTextField" cols="30" id="id_title" maxlength="30"
                          name="title" required=""
                          rows="1"></textarea>
            </div>
            <div class="field-title ">
                <label class="required" for="id_phone_number">Ведіть номер телефону:</label>
                <textarea placeholder="Ведіть Ваш номер..." name="phone_number" cols="30" rows="1"
                          class="vLargeTextField" maxlength="20" required=""
                          id="id_phone_number"></textarea>
            </div>
        </div>
        <div class="wrap-text">
            <div class="form-row field-Моцарелла">
                <div class="checkbox-row">
                    <input id="id_Моцарелла" name="Моцарелла" type="checkbox"><label class="vCheckboxLabel"
                                                                                     for="id_Моцарелла">🧀
                    Моцарелла</label>
                </div>
            </div>
            <div class="form-row field-Подвійний сир">
                <div class="checkbox-row">
                    <input id="id_Подвійний сир" name="Подвійний сир" type="checkbox"><label class="vCheckboxLabel"
                                                                                             for="id_Подвійний сир">🧀🧀
                    Подвійний
                    сир</label>
                </div>
            </div>
            <div class="form-row field-Бекон ">
                <div class="checkbox-row">
                    <input id="id_Бекон " name="Бекон " type="checkbox"><label class="vCheckboxLabel"
                                                                               for="id_Бекон ">🥓 Бекон </label>
                </div>
            </div>
            <div class="form-row field-Курка ">
                <div class="checkbox-row">
                    <input id="id_Курка " name="Курка " type="checkbox"><label class="vCheckboxLabel"
                                                                               for="id_Курка ">🍗 Курка </label>
                </div>
            </div>
            <div class="form-row field-Шинка">
                <div class="checkbox-row">
                    <input id="id_Шинка" name="Шинка" type="checkbox"><label class="vCheckboxLabel"
                                                                             for="id_Шинка">🍖 Шинка</label>
                </div>
            </div>
            <div class="form-row field-Зелень">
                <div class="checkbox-row">
                    <input id="id_Зелень" name="Зелень" type="checkbox"><label class="vCheckboxLabel"
                                                                               for="id_Зелень">🥒 Зелень</label>
                </div>
            </div>
            <div class="form-row field-Ананас">
                <div class="checkbox-row">
                    <input id="id_Ананас" name="Ананас" type="checkbox"><label class="vCheckboxLabel"
                                                                               for="id_Ананас">🍍 Ананас</label>
                </div>
            </div>
            <div class="form-row field-Оливки ">
                <div class="checkbox-row">
                    <input id="id_Оливки " name="Оливки " type="checkbox"><label class="vCheckboxLabel"
                                                                                 for="id_Оливки ">🍈 Оливки </label>
                </div>
            </div>
            <div class="form-row field-Помідори">
                <div class="checkbox-row"></div>
            </div>
            <div class="form-row field-Мариновані огірки">
                <div class="checkbox-row">
                    <input id="id_Мариновані огірки" name="Мариновані огірки" type="checkbox"><label
                        class="vCheckboxLabel"
                        for="id_Мариновані огірки">🥒 огірки</label>
                </div>
            </div>
            <div class="form-row field-Перець">
                <div class="checkbox-row">
                    <input id="id_Перець" name="Перець" type="checkbox"><label class="vCheckboxLabel"
                                                                               for="id_Перець">🌶 Перець</label>
                </div>
            </div>
            <div class="form-row field-Шампіньйони">
                <div class="checkbox-row">
                    <input id="id_Шампіньйони" name="Шампіньйони" type="checkbox"><label class="vCheckboxLabel"
                                                                                         for="id_Шампіньйони">🍄
                    Шампіньйони</label>
                </div>
            </div>
            <div class="form-row field-Кукурудза">
                <div class="checkbox-row">
                    <input id="id_Кукурудза" name="Кукурудза" type="checkbox"><label class="vCheckboxLabel"
                                                                                     for="id_Кукурудза">🌽
                    Кукурудза</label>
                </div>
            </div>
        </div>
        <button type="submit" class="create-btn">Створити</button>
    </form>
</div>
</body>
</html>

templates/deserts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deserts</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'animat.css' %}"/>
    <link rel="stylesheet" href="{% static 'desert.css' %}"/>

</head>
<body>
<header class="header container">
    <div class="wrap-content">
        <ul class="flex-nav">
            <li>
                <a href="{%url 'home'%}" class="">Головна
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{%url 'pizzas'%}">Піцца
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="#" class="bg-a">Десерти
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{%url 'drinks'%}">Напої
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
        </ul>
    </div>
</header>
<section class="main-section">
    <div class="container">
        <div class="h2">
            <h2>Наші <span class="bg-span">десерти</span></h2>
        </div>
        <div class="wrap-content">
            <form method="POST" class="flex-form">
                  {% csrf_token %}
                {% for desert in deserts %}
                <div class="first-item">
                    <img class="rounded" src="{{ desert.photo.url}}" width="300" height="230">
                    <p class="mg"><span class="bg-span">Назва:</span> {{ desert.title }}</p>
                    <p class="mg"><span class="bg-span">Маса:</span> {{ desert.mass }}</p>
                    <p class="mg"><span class="bg-span">Ціна:</span> {{ desert.price }}</p>
                                            <p class="qqq">Ведіть <span class="bg-span">ім'я</span> користувача:</p> {{ order.user }}
                        <p class="qqq">Ведіть <span class="bg-span">номер</span> телефону:</p> {{ order.phone_number }}
                    <button class="basket-btn " type="submit">Замовити</button>
                </div>
                {% endfor %}
            </form>


        </div>
    </div>
    </div>
</section>

</body>
</html>

templates/drinks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Drinks</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'animat.css' %}"/>
    <link rel="stylesheet" href="{% static 'desert.css' %}"/>
</head>
<body>

<header class="header container">
    <div class="wrap-content">
        <ul class="flex-nav">
            <li>
                <a href="{% url 'home' %}" class="">Головна
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{% url 'pizzas' %}">Піцца
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{% url 'deserts' %}">Десерти
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="#" class="bg-a">Напої
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
        </ul>
    </div>
</header>
<section class="main-section">
    <div class="container">
        <div class="h2">
            <h2>Наші <span class="bg-span">напої</span></h2>
        </div>
        <div class="wrap-content">
            <form method="POST" class="flex-form">
            {% csrf_token %}
                {% for drink in drinkss %}
                    <div class="first-item">
                        <img class="rounded" src="{{ drink.photo.url }}" width="300" height="230">
                        <p class="mg"><span class="bg-span">Назва:</span> {{ drink.title }}</p>
                        <p class="mg"><span class="bg-span">Маса:</span> {{ drink.ml }}</p>
                        <p class="mg"><span class="bg-span">Ціна:</span> {{ drink.price }}</p>
                                                <p class="qqq">Ведіть <span class="bg-span">ім'я</span> користувача:</p> {{ order.user }}
                        <p class="qqq">Ведіть <span class="bg-span">номер</span> телефону:</p> {{ order.phone_number }}
                        <button class="basket-btn " type="submit">Замовити</button>
                    </div>
                {% endfor %}
            </form>
        </div>
    </div>
</section>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'master.css' %}"/>
    <link rel="stylesheet" href="{% static 'menu.css' %}"/>
    <link rel="stylesheet" href="{% static 'animat.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>
<header class="header">
    <div class="wrap-content">
        <ul class="flex-nav">
            <li class="wrap-img-list">
                         <img  src="../static/icon/logo.png" style="margin-right: 15vw" class="logo" width="170px" height="70px" alt="">
                    </li>
            <li>
                <a href="#" class="bg-a">Головна
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{%url 'pizzas'%}">Піцца
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{%url 'deserts'%}">Десерти
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{%url 'drinks'%}">Напої
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
        </ul>
    </div>
</header>
<section class="main-section">
    <div class="container">
        <div class="hold-content">
            <div class="name-com">
                <h2 class="name_r">it <span class="bg-pizza">pizza </span>🍕</h2>
            </div>
            <div class="wrap-text">
                <p class="about">Піцерія «IT PIZZA» - це стильне молодіжне, сімейне заклад Черкас, вже давно
                    зарекомендувало себе серед жителів міста як місце з відмінною атмосферою, в якому можна не тільки
                    замовити піцу і покуштувати цікаві страви авторської італійської кухні, а й чудово відпочити.</p>
            </div>
            <div class="wrap-btn">
                <a target="_blank" href="https://web.telegram.org/#/im?p=@pizza_menu_bot" id="order" class="order">Замовляй
                    швидше
                    <img src="http://panda-test.dev.visacrm.com/img/telega.png" id="telega" class="telega" alt="">
                </a>
            </div>
        </div>
    </div>
</section>


<!--це домашня сторінка на якій все буде контакти про нас-->
<!--{% url 'log-out' %} це засуваєш в кнопку або ссилку коли нажимаєш воно виходе-->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script type="text/javascript">
    $(function () {
        /*--------- show and hide the menu  ---*/
        $('.button').on("click", function () {
            if ($('body').hasClass('nav_is_visible') == true) {
                $('body').removeClass('nav_is_visible');
                $('.button').removeClass('close');
            } else {
                $('body').addClass('nav_is_visible');
                $('.button').addClass('close');
            }
        });

        $('body').addClass('home_is_visible');


        function removeClasses() {
            $(".menu ul li").each(function () {
                var custom_class = $(this).find('a').data('class');
                $('body').removeClass(custom_class);
            });
        }

        $('.menu a').on('click', function (e) {
            e.preventDefault();
            removeClasses();
            var custom_class = $(this).data('class');
            $('body').addClass(custom_class);
        });
    });
</script>

</body>
</html>

templates/log_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Ввійти</button>
</form>
</body>
</html>

templates/pizzas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pizzas</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'pizza.css' %}"/>
    <link rel="stylesheet" href="{% static 'animat.css' %}"/>
    <link rel="stylesheet" href="{% static 'style_ingridients.css' %}"/>
</head>
<body>
<header class="header container">
    <div class="wrap-content">
        <ul class="flex-nav">
            <li>
                <a href="{% url 'home' %}" class="">Головна
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a class="bg-a" href="#">Піцца
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{% url 'deserts' %}">Десерти
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
            <li>
                <a href="{% url 'drinks' %}">Напої
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </li>
        </ul>
    </div>
</header>
<section class="main-section">
    <div class="container flex-cont">
        <div class="wrap-h2">
            <div class="wrap-new">
                <a href="{% url 'create_pizza' %}" class="your_pizza">Створи свою 🍕</a>
                <div class="hold-new">
                    <img class="img-new" src="https://image.flaticon.com/icons/svg/891/891448.svg" width="40px"
                         height="40px" alt="">
                </div>
            </div>
            <div class="full">
                <h2>Наші <span class="bg-span">піцци</span></h2>
            </div>
        </div>
        <div class="wrap-items">
            <form method="POST" class="form-flex">
              {% csrf_token %}
                {% for pizza in pizzas %}
                    <div class="first-item item">

                        <div class="photobox photobox_type10">
                            <div class="photobox__previewbox">
                                <img src="{{ pizza.photo.url }}" width="300px" height="230px">
                                <span class="photobox__label">
                                    <form >

                                         <p class="p-test">{{ pizza.description }} <br><p>

                                    </form>

                                    </span>
                            </div>
                        </div>
                        <p class="name-pizza mar"><span class="bg-span">Назва:</span> {{ pizza.title }}</p>
                        <!--                    <p class="name-pizza mar"><span class="bg-span">Інгрідієнти:</span> {{ pizza.description }}</p>-->
                        <p class="massa mar"><span class="bg-span">Маса :</span> {{ pizza.mass }}</p>
                        <p class="price mar"><span class="bg-span">Ціна:</span> {{ pizza.price }}</p>
                        <p class="qqq">Ведіть <span class="bg-span">ім'я</span> користувача:</p> {{ order.user }}
                        <p class="qqq">Ведіть <span class="bg-span">номер</span> телефону:</p> {{ order.phone_number }}
                        <button type="submit" class="mar basket-btn">Замовити</button>
                    </div>
                {% endfor %}
            </form>

            <div class="second-item item">

            </div>
        </div>
    </div>
</section>


</body>
</html>

templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
sign up
<form method="POST">
{% csrf_token %}
{{ profile_form.as_p }}
{{ user.as_p }}
<button type="submit">зарєгаться</button>
</form>
</body>
</html>